name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        
    - name: Create venv
      run: |
        uv venv
        
    - name: Install dependencies
      run: |
        uv pip install -e ".[test]"
        
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
      
    - name: Run tests with coverage
      run: |
        pytest --cov=memory_mcp_server --cov-report=xml --benchmark-only
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
